### ISSUE TITLE
Data element circular reference detected

### ISSUE THREAD

**Issue by alcazes** [adobe/reactor-extension-cloud-connector-edge#5] opened 2023-10-31 11:39 UTC
### Expected Behaviour

We should be able to reference a data element inside another data element

### Actual Behaviour

Error
```json
{
    "name": "evaluatingRule",
    "timestampMs": 1698750499741,
    "attributes": {
        "logLevel": "error"
    },
    "messages": [
        "🚀",
        "Failed to execute \"Make Fetch Call\". Data element circular reference detected: platform -> eventType -> lifecycleShortCode -> eventType \n Error: Failed to execute \"Make Fetch Call\". Data element circular reference detected: platform -> eventType -> lifecycleShortCode -> eventType\n    at worker.js:1:6395\n    at worker.js:1:6063\n    at Array.map (<anonymous>)\n    at worker.js:1:5979\n    at getSettings (worker.js:1:10866)\n    at worker.js:1:6602\n    at worker.js:1:6063\n    at Array.map (<anonymous>)\n    at worker.js:1:5979\n    at getSettings (worker.js:1:13752)"
    ],
    "logLevel": "log",
    "context": {
        "ruleId": "RL8ff0fa7212044c8292174187be01e09f"
    }
},
```

#### Sample Code that illustrates the problem

There seems to be a bug in Adobe Event Forwarding:
 ![Event Forwarding Error](https://github.com/adobe/reactor-extension-cloud-connector-edge/assets/8456933/bc6bc5be-6705-461c-aa50-2a9190d9d006)

Data Elements are as follow:
![data elements](https://github.com/adobe/reactor-extension-cloud-connector-edge/assets/8456933/5b091f6d-3aa2-46ab-a27d-cfacded862e3)
 
platform
![platform](https://github.com/adobe/reactor-extension-cloud-connector-edge/assets/8456933/d52fb99c-f2a0-4d8c-b1aa-a933da09017f)

eventType
![eventType](https://github.com/adobe/reactor-extension-cloud-connector-edge/assets/8456933/7cb35f6d-f1cb-47c5-9526-6b64214d3a42)
 
lifecycleShortCode
![lifecycleShortCode](https://github.com/adobe/reactor-extension-cloud-connector-edge/assets/8456933/8e1d2525-11a1-4278-a153-0b060d30989f)

**Comment by dompuiu** [comment] 2023-11-01 17:39
@alcazes Can you provide a URL of the rule where you see this error. Or provide a screenshot of the Make Fetch call action config? Thanks!

**Comment by alcazes** [comment] 2023-11-02 07:37
@dompuiu the URL is https://experience.adobe.com/#/@rbs/sname:prod/data-collection/eventForwarding/companies/COe5253eb028b44a8dbe0d4830477b7be6/properties/PR3f4c299f27f541dfbcd290cd3b62a916/rules/RL4c17b6ad344544e292dc5ac035f1c21f/ruleComponent/RCf5fc04e3ad5f4f63b27c6d44693ff1cb

The part of the rule which creates the issue is this one:
![image](https://github.com/adobe/reactor-extension-cloud-connector-edge/assets/8456933/4ab41f1f-8bf6-4763-8d2d-3bc1deb31a8f)

I also opened an issues on https://github.com/adobe/reactor-extension-core-edge/issues/7 for the same behaviour.

I dig a bit dipper and I believe the issue is no even with your extensions but the turbine source code:
https://github.com/adobe/reactor-turbine-edge/blob/2117c319c32ed3315e004dc027da348eba18a5b3/src/createGetDataElementValue.js#L38

```js
if (dataElementCallStack.includes(dataElementName)) {
    dataElementCallStack.push(dataElementName);

    return Promise.reject(
        new Error(
            `Data element circular reference detected: ${dataElementCallStack.join(
            ' -> '
          )}`
        )
    );
}
```

Based on this code you cannot create a data element to be reused in other data elements like in my case:
* `eventType` is initially used in the Fetch to return a value
* `lifecycleShortCode` is then used in payload of the Fetch request to return the application lifecycle and the logic of this data element relies on `eventType` to return correct value. 
* Based on code snipset above the following eventName will be pushed in call stack `eventType` ==> `lifecycleShortCode` ==> `eventType`. When last `eventType` is pushed the circular reference error will be triggered.

Based on all that it seems that for now you cannot use a data element in other data elements as you would do with Adobe Launch. 

I also create an Adobe support ticket for same `E-001072880`

Should I open an issue against reactor-turbine or your team will follow up ?

**Comment by dompuiu** [comment] 2023-11-02 15:58
Yes, the issue is in `reactor-turbine-edge`. Thanks for logging this issue. We'll take it from here.

**Comment by dompuiu** [comment] 2023-11-16 22:49
This issue is fixed in this release: https://github.com/adobe/reactor-turbine-edge/releases/tag/v2.3.3.

**Closed as completed by dompuiu** 2023-11-16 22:49 UTC

**Comment by dompuiu** [comment] 2024-01-17 21:03
This fix was deployed today in production.
